# Generated by Django 6.0.4 on 2026-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("loan_created", "Loan Created"),
                    ("return_receipt", "Return Receipt"),
                    ("overdue_reminder", "Overdue Reminder"),
                    ("reservation_available", "Reservation Available"),
                ],
                max_length=50,
            ),
        ),
    ]
