# Generated by Django 6.0.4 on 2026-04-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="core.institution",
            ),
        ),
        migrations.AddField(
            model_name="librarybranch",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library_branches",
                to="core.campus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campus",
            unique_together={("institution", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="librarybranch",
            unique_together={("campus", "code")},
        ),
    ]
