# Generated by Django 6.0.4 on 2026-04-15 16:20

import apps.circulation.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loaned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["-loaned_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("available", "Available"),
                            ("fulfilled", "Fulfilled"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("queue_position", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["queue_position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "return_token",
                    models.CharField(
                        default=apps.circulation.models.generate_return_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
