# Generated by Django 6.0.4 on 2026-04-15 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("circulation", "0001_initial"),
        ("core", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="checked_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="item_copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="catalog.itemcopy",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="patron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="users.patron",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="bibliographic_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="catalog.bibliographicrecord",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="fulfilled_item_copy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_reservations",
                to="catalog.itemcopy",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="patron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="users.patron",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="pickup_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="core.librarybranch",
            ),
        ),
        migrations.AddField(
            model_name="returnreceipt",
            name="loan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_receipt",
                to="circulation.loan",
            ),
        ),
        migrations.AddField(
            model_name="returnreceipt",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
