# Generated by Django 6.0.4 on 2026-04-15 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BibliographicRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=32)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(default="pt-BR", max_length=30)),
                ("edition_statement", models.CharField(blank=True, max_length=100)),
                ("classification_code", models.CharField(blank=True, max_length=50)),
                ("cutter", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="records", to="catalog.author"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ItemCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_code", models.CharField(max_length=50, unique=True)),
                ("tomb_number", models.CharField(blank=True, max_length=50)),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                (
                    "rfid_tag",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("shelf_location", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("loaned", "Loaned"),
                            ("reserved", "Reserved"),
                            ("processing", "Processing"),
                            ("lost", "Lost"),
                            ("discarded", "Discarded"),
                        ],
                        default="available",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bibliographic_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="catalog.bibliographicrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_code"],
            },
        ),
    ]
