# Generated by Django 6.0.4 on 2026-04-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcopy",
            name="library_branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="core.librarybranch",
            ),
        ),
        migrations.AddField(
            model_name="bibliographicrecord",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="records", to="catalog.subject"
            ),
        ),
    ]
